### ISSUE TITLE
Fix bitrise/amazon s3/google play store integration

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-mobile#849]
Bitrise builds are failing to upload to our Amazon s3 bucket.

See build fail [here](https://app.bitrise.io/build/9d7df6e6-0ec7-406d-945a-73bad21481de#?tab=log)

## Desired Behaviour
The APK should automatically be uploaded to amazon s3 and the google play store.

**Comment by achou11** [comment]
Suspicion is that this is on Bitrise's end with some issue with the environment for their s3 uploader. Not sure if there's anything we can do on our end to fix at the moment

**Comment by achou11** [comment]
Error on bitrise for extra context:

```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 69, in main
    driver = create_clidriver()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 79, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "/usr/local/lib/python2.7/dist-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/lib/python2.7/dist-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/local/lib/python2.7/dist-packages/awscli/handlers.py", line 27, in <module>
    from awscli.customizations.cloudformation import initialize as cloudformation_init
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/cloudformation/__init__.py", line 13, in <module>
    from awscli.customizations.cloudformation.package import PackageCommand
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/cloudformation/package.py", line 26, in <module>
    from awscli.customizations.s3uploader import S3Uploader
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3uploader.py", line 22, in <module>
    from s3transfer.manager import TransferManager
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/__init__.py", line 134, in <module>
    import concurrent.futures
ImportError: No module named concurrent.futures
Failed to upload file
```
